linters:
    LineLength:
        max: 120
        severity: error
    Indentation: # For consistency with default rubocop rules.
        character: space
        width: 2
        severity: error

exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
